### ISSUE TITLE
Monsters attack at a distance/through walls

### ISSUE THREAD

**Issue by pirate486743186** [Soviet5lo/SlashTHEM#10]
A lillend attacks me through the wall!!!! also similar problem with a cacodemon!!!
I have displacement and extrinsic telepathy.
These two have ranged attacks, while it seams monsters with out ranged attacks behave as expected.
The combination of the three is the bug? (extrinsic telepathy, displacement and ranged attack)?

(you can check the same save file i sent for -45AC)

(more details lillend)
She summoned monsters, and "The invisible lillend brushes against your leg."
She was in a touret, i was in the adjacent storehouse. in an alternate castle version

Next, i was on the  open space out side the castle, at the back door.
Something like 5 squares in the diagonal from her, and a wall in between (she was still in the touret).
I get again "The invisible lillend brushes against your leg."

(more details cacodemon)
i get "Gaze attack 242?"
He is in a storage room, i'm in the throne room

**Comment by Soviet5lo** [comment]
This is considered a bug, despite being intentionally added as a feature in Slash'EM Extended.  This will not exist in the next version, but quite a few monsters have bugged attacks.  For those, that will be taken care of in a preview release (Version 0.9?) after I do a massive role, race, monster and object cleanup.

**Comment by Soviet5lo** [comment]
should be fixed in the latest preview
