### ISSUE TITLE
Mirror Brand Artifact Alignment - is it supposed to be neutral?

### ISSUE THREAD

**Issue by theonlyalterego** [Soviet5lo/SlashTHEM#13]
All the other brands are unalign, but the artifact code has Mirror Brand being Neutral ; is that intended?

A("Mirror Brand",                 SILVER_LONG_SWORD, /* dNethack */
	(SPFX_RESTR|SPFX_ATTK|SPFX_REFLECT|SPFX_DALIGN), 0, 0,
	STUN(5,0),	NO_DFNS,	NO_CARY,	0, A_NEUTRAL, NON_PM, NON_PM, 3500L ),

**Comment by Soviet5lo** [comment]
It's intended, aside from the base object and the to-hit bonus it's exactly the way it was in dNethack.
