### ISSUE TITLE
critical bug, Vlad tower levels as room and corridors levels

### ISSUE THREAD

**Issue by pirate486743186** [Soviet5lo/SlashTHEM#15]
One or more levels of the Vlad tower can be replaced with rooms and corridors levels.

Some levels can be there.
You can get the first level as a rooms and corridors level.
When you go up, it lands you at a random place in the usual second level.
If you try to go down, the game gets stuck. It hasn't crashed, but it's impossible to continue.

Or all the levels are rooms and corridors. It doesn't crash or get stuck.
But there is no candelarium any more....

**Comment by Soviet5lo** [comment]
Should be fixed as of commit 1b4d9407d81f8843bba1c499cecff97ffd2aaddf
