### ISSUE TITLE
wizard mode wishing faillure

### ISSUE THREAD

**Issue by pirate486743186** [Soviet5lo/SlashTHEM#16]
In wizard mode, i can't wish for "The Burned Moth Relay" and "pack of floppies".
I copy pasted exactly from the source, it still complain it doesn't exist...

**Comment by AmyBSOD** [comment]
Parser quirk with item names that end in a "s": you'll have to wish for "pack of floppiess" instead.

**Comment by pirate486743186** [comment]
an other little mistake of the same kind
"12 box containing little plastic cardses"

**Comment by Ozma777** [comment]
I had that problem with the artifact "Blunderbuss" rifle in my pirate class....
Had to wish for "rifle named Blunderbuss" Of course next time I will wish for Blunderbusss and see if that will work.
