### ISSUE TITLE
floppies and electronics

### ISSUE THREAD

**Issue by pirate486743186** [Soviet5lo/SlashTHEM#17]
What do you do with this stuff??
I tried to look in the "Nethack the new generation" readme, but it redirects me to "readme.DNA", but i don't see a readme.dna....
I couldn't find anything on the net either...

the "Hichhickers guide to the galaxy" seams to be a trap to be confused with the god-o-meter.
the god-o-meter tells you if you can pray..
I think i got these right.

The IC, relay, transistor, diode seam to be corpse parts for the computer monsters. Right?
ICs seam quite expensive for them been useless.
Yea yea, also relay is the base item for the burned moth relay

What do you do with the floppies???? The geek can read them so that he get confused?
yea yea, they are also the base item for "The Nethack Sources" and "Master Boot Disk"

**Comment by Ozma777** [comment]
I think that the floppies should be linked to Shuriken skill and should be able to be thrown (maybe just by geeks) like shurikens (especially the old style floppies). Maybe (like iron ball and Convicts exercises flail skill) someone will get it to be able to exercise shuriken. I am hoping (IF I can ever get an ACTUAL geek patch off the internet that works) to make it do that.

**Comment by Soviet5lo** [comment]
The floppies are basically just a base item for the Geek/Hacker and Graduate/Geek roles.  I probably should set the computer parts to have no probability of being generated in the dungeon, honestly.
