### ISSUE TITLE
minor errors in messages

### ISSUE THREAD

**Issue by pirate486743186** [Soviet5lo/SlashTHEM#18]
"Astala vista, baby!" should be "Hasta la vista, baby!" (dat/quest.txt)
Unless it was supposed to be wrong? You know, because demons are evil and don't care.

The encyclopedia entry of "The Staff of Aesculapius", says that it protects against life draining.
But this is not true since slashem.

**Comment by Soviet5lo** [comment]
the line in quest.txt doesn't exist anymore.  The Staff protects against life drain again as of commit 33be746b.
