### ISSUE TITLE
ungenomic mold and prayer

### ISSUE THREAD

**Issue by Ozma777** [Soviet5lo/SlashTHEM#23]
So I was a level one Ungenomic Locksmith and I turned from some green (lowercase) L with 84 hitpoints and then 5 turns later with 6 monsters chasing me turned into a rattata with 3 hp! so I'm running away and I thought Youpoly (only had 10/10 mp) so nope needed 20....

I killed a few things in about 10 turns and got to level 2 rattata with 15 hp and 20 mp....

missed a bat about 100 times and was down to 1 hp and prayed (should have youpolyed but didn't see the 20mp

As soon as the prayer was over I was changed back to ungenomic mold thus ending the game less than 200 turns in.

Not sure if there is a way to make ungenomic molds keep their old form only regaining hp or not being fainting from starvation or dying of sickness after praying (or if it is even possible to code it like that)

But I think last time I was fainting as a ungenomic mold I insta-died then too when the gods changed me back.

Of course maybe this is just part of playing as an ungenomic mold and I should just deal with it.

**Comment by AmyBSOD** [comment]
In slashem extended all those things are fixed. Slashthem should incorporate those changes IMHO.

**Comment by Soviet5lo** [comment]
Probably a case of ungenomolds not having an exception for the "polymorphed" trouble for prayer.  This isn't valid now due to ungenomolds not existing in develop.
