### ISSUE TITLE
README fixes

### ISSUE THREAD

**Issue by moon-chilled** [Soviet5lo/SlashTHEM#27]
Link syntax is off in a couple of places (e.g. `[here] (https://github.com/Soviet5lo/SlashTHEM/blob/master/CHANGELOG.md)` and `[releases] (https://github.com/Soviet5lo/SlashTHEM/releases)`)--shouldn't have a space between ] and (.

Slash'EM-Next was always a working title; I've decided to call it Slash'EM9; includes lots of other changes, including balance tweaks, and update to nethack 3.6.

Also, welcome back!  It's been a while :)

**Comment by Soviet5lo** [comment]
Huh, I suppose Gitea is more lenient when it comes to syntax for markdown files.  Fixed, as well as a few other updates relating to Slash'EM-Next/Slash'EM9
![Screenshot_2020-02-02_18-37-12](https://user-images.githubusercontent.com/10472297/73618191-73c2d180-45eb-11ea-9877-e878cdbfbc58.png)
And thank you.  Figured I might as well upload what I've done the past year or so.
