### ISSUE TITLE
Castle Variant Throne Room Bug

### ISSUE THREAD

**Issue by shadowrider38** [Soviet5lo/SlashTHEM#39]
On the castle level, I can produce the message "You have entered an opulent throne room!" while still inside the armor/weapon storerooms when moving on tiles close to the actual throne room. Would appear to be some sort of mapping oversight, possibly variant layout is written on top of the original castle map code.

**Comment by Soviet5lo** [comment]
Hmm.  I'm assuming its castle variants 4, 5 or 6.  1 is default and 2/3 come from the [New Castle Levels](https://bilious.alt.org/?27) patch.

**Comment by shadowrider38** [comment]
Did you want me to go back and take a picture of the variant? If there are pictures of the variant maps I could also look through those

**Comment by Soviet5lo** [comment]
I found it, it's castle variant 5.  Looks like the throne room isn't rectangle shaped but instead has a walled section on the bottom right that includes part of one of the storerooms.

**Comment by shadowrider38** [comment]
Yes that sounds about right to me, I imagine it shouldn't be too tricky to fix.

**Comment by Soviet5lo** [comment]
Fixed in a0ed9319 by modifying the layout a bit; shifted one of the dragons to the top secret path to the storerooms (3 in one passageway might be a tad too much?)

By the way, congrats on finishing the Nethackathon run.

**Comment by shadowrider38** [comment]
Thanks so much!
