### ISSUE TITLE
Gibberling/Grimlock murder

### ISSUE THREAD

**Issue by pirate486743186** [Soviet5lo/SlashTHEM#4]
As a human samurai, i killed a hostile Gibberling, and i got "you murderer" message.
They are considered human if you eat them. 

I tested in wizard mode. This seams to happen after the first one you kill.
You don't lose telepathy, but you do get a luck penalty (-6).
You alignment doesn't change, but the max alignment does change. I got 10 alignment, and -5 max alignment.

It seams that the above remain true also for Grimlocks.
This is definitely a bug and not a slex "feature".
It's not a slashem bug either.

**Comment by pirate486743186** [comment]
This is definitely a bug by the way.

**Comment by pirate486743186** [comment]
Maybe related, i also got these two.

You kill Arthur Dent!  You murderer!
You kill Ford Perfect!  You murderer!

I'm sure they were hostile.

**Comment by AmyBSOD** [comment]
xkilled function in mon.c, already fixed in slex.

**Comment by Soviet5lo** [comment]
Fixed in develop.  I decided to just strictly check for always_peaceful, instead of !always_hostile then doing a second check for always_peaceful a bit afterward as it's done in slash'em extended.

**Comment by pirate486743186** [comment]
Wait a minute.
I got a hostile gypsy once in the lawful quest.
That is covered?

**Comment by AmyBSOD** [comment]
At least in slex as a ValHumFemLaw, killing a hostile gypsy gives no penalty. It should be the same in slashthem. Killing the hostile coaligned unicorn on the lawful quest, on the other hand, is a *terrible* idea.

**Comment by Soviet5lo** [comment]
Okay, from doing some testing in Wizard mode...

All of these are using a Lawful Human Male Samurai, First killing a hostile gypsy and second killing a gibberling.

Slash'EM: No alignment change, no murder message, no luck change when killing either of them.

Slash'EM Extended: No alignment change when killing a hostile gypsy, -2 to alignment when attacking a gibberling, no murder message on either, no luck lost.

SlashTHEM (with the current "fix"): Murder message and -5 to alignment and max alignment and -2 luck penalty when killing gypsy, no alignment change/murder message/luck change when killing a gibberling.

I'm reopening this issue for now, as it seems both Slash'EM Extended and SlashTHEM don't function the same as Slash'EM in this case.

**Comment by pirate486743186** [comment]
It's not possible to simply revert back to slash'em way of doing this?

**Comment by Soviet5lo** [comment]
It's been reverted as of commit cc64d5d.
