### ISSUE TITLE
Option hitpointbar isn't working?

### ISSUE THREAD

**Issue by transcendreamer** [Soviet5lo/SlashTHEM#41]
Tried with statuscolor and without: hit-point bar is always empty... but brackets are drawn though...

**Comment by Soviet5lo** [comment]
Hmm, odd.  Is this a local build or hardfought?

**Comment by transcendreamer** [comment]
Hardfought server, same problem at console and web-terminal.

![image](https://user-images.githubusercontent.com/46658406/133005535-2ba2b897-8dfa-4e2f-af0b-611a27bbe7fc.png)

![image](https://user-images.githubusercontent.com/46658406/133005583-3c55c216-13da-4e91-b7b3-c058ade39cf0.png)

**Comment by moon-chilled** [comment]
OPTIONS=use_inverse

**Comment by transcendreamer** [comment]
Oh, didn't know about this option, sorry for bothering you.
Now HP bar works just fine, thank you very much!
