### ISSUE TITLE
"Only tools wouldn't buy our tools!"

### ISSUE THREAD

**Issue by transcendreamer** [Soviet5lo/SlashTHEM#42]
Probably it should be as follows? -  "Only **_fools_** wouldn't buy our tools!" (shopkeeper's speech)

**Comment by moon-chilled** [comment]
Calling somebody a 'tool' is an idiom and an insult.  I expect it is intentional.

**Comment by transcendreamer** [comment]
That makes sense, yes. 
At first I was thinking it was mistyped because of using the word "tool" twice.

**Comment by Soviet5lo** [comment]
This is fully intended, pulled straight from Sporkhack.
