### ISSUE TITLE
Since your weapon is welded to your hand, you cannot wield that torch.

### ISSUE THREAD

**Issue by transcendreamer** [Soviet5lo/SlashTHEM#43]
Is that correct/intended? 
I have applied a cursed torch, now it is welded, but I can not ignite it.
And the strangest thing: I do not see the torch in my used items list with "*" command, nothing is wielded.

**Comment by moon-chilled** [comment]
Possibly related to [this](https://github.com/SLASHEM-Extended/SLASHEM-Extended/commit/007da02516e7382aaec606533904d53db471d4b5) bug which was fixed in slex?

**Comment by Soviet5lo** [comment]
This should be fixed in 07ec296, oops.
