### ISSUE TITLE
If you save after ordering an artifact weapon at the forge, the blacksmith forgets about it

### ISSUE THREAD

**Issue by amateurhourrrr** [Soviet5lo/SlashTHEM#44]
Probably an oversight that exists in Nethack TNG as well

Because they forget, you can essentially pour tens of thousands of gold down the drain if you can't wait out the time in your current session

**Comment by Soviet5lo** [comment]
This is definitely an oversight in TNG as well.  Unfortunately I'm certainly not knowledgeable enough when it comes to saving, so I wouldn't necessarily know how to resolve this properly.

I've thought about reducing the time it takes for an artifact to be made, but this wouldn't really fix the issue at hand.

**Comment by amateurhourrrr** [comment]
I think (but haven't checked or anything) it might be possible to change artifact name and time remaining (in `src/smith.c`) to be no longer static so they can be `extern`'d, and adding them to `savegamestate` and `restgamestate`

I think that might be enough, but it'd need checking (and it'd break current saves)

**Comment by amateurhourrrr** [comment]
Took a look at this in lunch break, will try to submit a PR after work

**Comment by amateurhourrrr** [comment]
closed by #45
