### ISSUE TITLE
The wand of might doesn't recharge to 1:3

### ISSUE THREAD

**Issue by amateurhourrrr** [Soviet5lo/SlashTHEM#53]
The recharging code was changed to be vanilla, but it sets limit to 2 for wands of wishing where vanilla set it to 3, the comparison later on in the recharging code checks specifically for lim == 3

This means that you can blessed recharge the wand of might and get a 1:1 wand instead of a 1:3 wand

Maybe this is intentional, I'm not sure

**Comment by Soviet5lo** [comment]
I went ahead and fixed this in 202ed127
