### ISSUE TITLE
Nighthorn turns to dust

### ISSUE THREAD

**Issue by pirate486743186** [Soviet5lo/SlashTHEM#6]
I tested this in wizard mode. If you apply Nighthorn, it turns to dust as with any vulgar unicorn horn.
Is this intended behaviour?

**Comment by Elronnd** [comment]
As a matter of fact, the fact that any unicorn horn turns to dust is an unwanted feature and will be removed as soon as possible.  However the bug is probably reproducible in Slash'EM Extended, so you should test that and if so then report it to the maintainer.

**Comment by pirate486743186** [comment]
slashem extended doesn't compile again.... B[

kwests.des : 2 errors detected. No output created!
make[1]: *** [spec_levs] Segmentation fault
make[1]: Leaving directory `/home/mike/slashemextended/SLASHEM-Extended/dat'
make: *** [spec_levs] Error 2

****  Installation failed. Aborting package creation.

I think the makefiles need updating

**Comment by pirate486743186** [comment]
Told her

**Comment by Soviet5lo** [comment]
The unicorn horn being turned into dust thing has been disabled for now to compensate for unicorn horns being so difficult to come by, due to the large amount of added monsters.  The code now also checks and avoids destroying Nighthorn, whenever I decide to re-enable this particular feature.
