### ISSUE TITLE
Hacker quest levels fail to generate

### ISSUE THREAD

**Issue by shadowrider38** [Soviet5lo/SlashTHEM#82]
I get the "Couldn't load Hac-fila.lev - making a maze" message for all of the hacker quest levels. The goal level spawned an open room of ice and regular floor, but no Bill Gates, QA, or Bell of Opening. It might just have to do with the fact that I could not accept the quest because there was no quest leader either. I'm assuming this game is unwinnable now?

**Comment by amateurhourrrr** [comment]
I suspect it happened because of your previous crashes with the heisenbugs - there seems to be something going wrong with crash recovery destroying files, we saw this too with malor's game crash

fwiw the heisenbug crash has an open pull request for it so it shouldn't happen again once that's merged

**Comment by shadowrider38** [comment]
I might agree that the heisenbugs were creating the issue except that the first one I killed was on the quest home level, which had already generated incorrectly. Unless the heisenbug issue affects the game on level gen? This was the first crash of the entire game.

**Comment by amateurhourrrr** [comment]
oh the quest start floor was already broken before you'd crashed due to killing a heisenbug?

that sounds like something completely different then yeah, maybe worth checking with K2 if the game files are all there

**Comment by amateurhourrrr** [comment]
Demo figured it out, the des files have the level names wrong for both Geek and Hacker after their respective renames

I'll open a PR for it now
