### ISSUE TITLE
Does `SPFX_DEFN` do anything?

### ISSUE THREAD

**Issue by wolfadactyl** [Soviet5lo/SlashTHEM#87]
Was looking through the list of artifacts and noticed both Firewall and Excalibur have `SPFX_DEFN`, however in searching the codebase I only see it as defined and not read anywhere. Am I right in thinking that it has no impact or am I missing something?

**Comment by amateurhourrrr** [comment]
Heya!

I think you're right that it does nothing 

I checked various variants and versions of vanilla to see if I could find it ever doing something, and it seems like it never has, not even in nethack 3.0.0 where it was introduced (unless I'm missing something)

My guess is that it was a label added intended for something then went unused

**Comment by wolfadactyl** [comment]
ha ok great, thanks! was looking through the source to see and found a few things that didn't add up like that so just wanted to check to make sure I wasn't crazy 😃
