### ISSUE TITLE
scary arch-lichen

### ISSUE THREAD

**Issue by pirate486743186** [Soviet5lo/SlashTHEM#9]
Status of the arch-lichen (neutral):  Level 126  HP 505(505)  Pw 370(370)  AC -78.

And i was wandering why i was keep missing B[ ....

**Comment by pirate486743186** [comment]
you did notice the -78 AC right? O_O
I left it in moloch temple in the save file..
An other masochistic slashem extended "feature"?

**Comment by Soviet5lo** [comment]
It's indeed another masochistic Slash'EM Extended "feature".  Expect this monster, along with a ton of others, to be removed in the the Version 0.9 test.
